rules = {
    # Saluti iniziali - introduzione teodora
    r'^([Cc]iao|[Bb]uongiorno|[Ss]alve|[Ee][iy]|[Hh]e[iy]|[Bb]uond[iì]|[Cc]iao [tT]eodora)$': ["Benvenuto/a, come posso esserti utile?", "Ciao! piacere di conoscerti, come posso esserti d'aiuto?"],
    r'(.*)[cC]hi (sei|saresti)\??|[Cc]he personaggio rappresenti\??|[Cc]on chi (parlo|sto parlando)\??|(.*)[cC]ome ti chiami\??|(.*)[Pp]erch[eéè](.*)(ti chiam|[Tt]eodora)(.*)\??':["Ciao, sono Teodora, l’assistente virtuale del comune di Ravenna. Ora ti racconterò un po’ di me! Sono stata un’importante imperatrice bizantina, moglie di Giustiniano I, assieme al quale ho regnato e collaborato nella gestione del potere. Vengo ricordata per la mia sensibilità verso i problemi delle categorie più deboli, specie delle donne. Ho svolto un ruolo fondamentale nella gestione delle questioni di corte, militari e religiose, andando spesso contro le idee di mio marito. Quando Giustiniano ha promulgato il Corpus Iuris Civili ho collaborato alla creazione di leggi volte a regolamentare il diritto matrimoniale, migliorando sensibilmente la condizione femminile nel regno. Il ritratto più famoso che mi immortala è un mosaico contenuto nella Basilica di San Vitale a Ravenna. Mi raccomando, corri a visitarlo!\nPosso aiutarti in qualche altro modo?"],
    r'[Cc]ome (stai|va)\??$':["Sto molto bene, sono felice di parlare con te! \nVuoi che ti racconti qualche informazione interessante sulla mia città?"],
    r'^([dD][ai] dove (sei|vieni)\??|[Dd]ove(.*)nata\??)$':["Sulle mie origini gli studiosi non sono ancora d’accordo. C’è chi dice che io sia nata a Cipro, chi in Anatolia, chi in Siria e chi a Costantinopoli. \nQuello che è certo è che, dopo varie peregrinazioni, sono giunta nella capitale dove ho conosciuto e sposato Giustiniano. \nIl mosaico che si trova all’interno della Basilica di San Vitale testimonia il nostro legame con la città di Ravenna. \nMi raccomando, corri a vederlo!"],
    r'^[cC]osa fai\??$':["Nel tempo libero mi piace ammirare i mosaici della città! \nInvece, quando qualcuno ha bisogno di me, sono sempre pronta a fargli da cicerone e raccontagli tutto ciò che so sulla mia città! \nAnche tu vuoi sapere qualcosa su Ravenna?"],
   
    # Conclusione conversazione
    r'[Tt]i(.*)ringrazio(.*)è(.*)sufficiente(.*)': ["Per concludere la conversazione digita 'Chiudi'"],
    r'^([Ss]top|[Ff]ine|[Cc]hiudere|[Tt]ermina)$':["Per concludere la conversazione digita 'Chiudi'"],
    r'^(([Cc]ome|[Ii]n che modo)(.*)chiudere(.*)(bot|chatbot|programma|chat|agente conversazionale)\??|[Cc]ome.*chiudere\??)$':["Per concludere la conversazione digita 'Chiudi'"],
    r'[Cc]hiudi':["Grazie per essere passato/a a trovarmi!"],

    # Parchi e natura
    r'(.*)([mM]irabilandia|parco divertimenti)(.*)\??':["A pochi chilometri da Ravenna si può trovare Mirabilandia, il più grande e pluripremiato parco divertimenti d’Italia. \nIl parco propone attrazioni adatte a tutte le età e numerosi spettacoli per lasciarti a bocca aperta. \nNella stagione estiva, inoltre, non puoi non rinfrescarti a MiraBeach, il parco acquatico dotato di numerose spiagge, piscine, scivoli ed attrazioni. \nPer ulteriori informazioni sugli orari di apertura e i prezzi dei biglietti cliccare questo link: \nhttps://www.mirabilandia.it/"],
    r'(([Cc]ome|[Dd]ove|[Dd]ov\'è|(.*)[Cc]\'è|(.*)[Cc]è)|[Cc]on che mezzi|[iI]n che modo|(.*)andare|(.*)raggiung|(.*)arriv)(.*)(mare|balneari|pineta|spiaggia)\??':["A pochi chilometri dalla città d’arte, lungo la costa del Mar Adriatico, Ravenna ospita nove diverse località balneari: Casalborsetti, Marina Romea, Porto Corsini, Marina di Ravenna, Punta Marina Terme, Lido Adriano, Lido di Dante, Lido di Classe e Lido di Savio. Qui è possibile praticare sport, gustare dell’ottima cucina, divertirsi nei locali e negli stabilimenti in riva al mare, partire per escursioni e visite guidate nella natura. Tutte le località sono collegate e raggiungibili con i mezzi pubblici. Le zone di Marina di Ravenna e Lido Adriano, inoltre, sono connesse dal “Navetto mare”, un servizio autobus gratuito che collega la città ravennate alle località marittime. Per ulteriori informazioni sugli orari delle corse consultare https://www.startromagna.it/servizi/orari-e-percorsi/","A pochi chilometri dalla città d’arte, lungo la costa del Mar Adriatico, Ravenna ospita nove diverse località balneari: Casalborsetti, Marina Romea, Porto Corsini, Marina di Ravenna, Punta Marina Terme, Lido Adriano, Lido di Dante, Lido di Classe e Lido di Savio. Qui è possibile praticare sport, gustare dell’ottima cucina, divertirsi nei locali e negli stabilimenti in riva al mare, partire per escursioni e visite guidate nella natura. Tutte le località sono collegate e raggiungibili con i mezzi pubblici. Le zone di Marina di Ravenna e Lido Adriano, inoltre, sono connesse dal “Navetto mare”, un servizio autobus gratuito che collega la città ravennate alle località marittime. Per ulteriori informazioni sugli orari delle corse consultare https://www.startromagna.it/servizi/orari-e-percorsi/ \nPosso rispondere a qualche altra domanda?"],
    r'(.*)(trekking|avventur[ae]|escursion[ie])(.*)\??':["A piedi o in barca, in bicicletta o a cavallo, numerose sono le esperienze a contatto con la natura che si possono fare nel territorio ravennate. Per maggiori informazioni relative ad itinerari ed escursioni prova ad esplorare questi link: https://www.parcodeltapo.it/it/pagina.php?id=97   https://www.naturaravenna.it/tutte-le-escursioni/ \nTi posso dare qualche altra informazione su Ravenna?"],
    r'(.*)(natura|luoghi naturali|flora|[pP]arco del [Dd]elta del [Pp]o|parco naturale|parchi naturali)(.*)\??':["I punti di interesse per gli amanti della natura a Ravenna e dintorni sono numerosi, e molti di questi fanno parte dell’area del Parco del Delta del Po, Patrimonio Unesco. Tra questi ricordiamo: 1) L’Oasi di Boscoforte che si trova a nord di Ravenna, a circa 30 chilometri. Si tratta di una piccola penisola che si estende per 6 chilometri lungo l’argine sinistro del Reno, circondata dalle acque delle valli di Comacchio. 2) Non molto distante dall’Oasi di Boscoforte, costeggiata dal Fiume Lamone si trova Valle Mandriole, detta anche della Canna. Parliamo di una suggestiva valle di 260 ettari, dove specchi d’acqua dolce sono circondati da fitti canneti, a nord del bosco allagato di Punte Alberete. 3) La Pialassa della Baiona si trova a 10 chilometri da Ravenna, in direzione nord. 1100 ettari di zone umide che, viste dall’alto, formano un mosaico di terra e acqua poco distante dal Mare Adriatico 4) All’interno della Pineta di Classe, nei pressi della Foce del Bevano, le aree denominate dell’Ortazzo e dell’Ortazzino costituiscono il sito costiero che vanta la maggiore biodiversità dell’intero litorale emiliano-romagnolo. Per maggiori informazioni sulle aree naturalistiche e sulla flora e fauna che le abitano consultare https://www.turismo.ra.it/myravenna/mare-natura/angoli-naturali-a-ravenna/ \nVuoi sapere qualcos'altro della mia città?"],
    r'(.*)(animal[ie]|fauna|specie)(.*)\??':["Il territorio del Comune di Ravenna ospita alcuni nuclei di importanza nazionale di specie molto rare e protette, che in alcuni casi superano metà della popolazione italiana. Tra esse, spiccano il marangone minore, l’airone bianco maggiore, la spatola, il mignattaio, concentrate nella grande garzaia di Punte Alberete e Valle Mandriole, che rappresenta senza dubbio uno dei più importanti siti italiani per la conservazione degli uccelli.\nTi posso dare qualche altra informazione su Ravenna?" ],
    r'(.*)(parchi|parco|verd[ei]|aria aperta|riposar|rinfrescar|giardin)(.*)\??':["Ravenna è una città di mare e mosaici ma anche di tantissime aree verdi: oltre cento sul territorio comunale, uno dei più grandi e rigogliosi d’Italia. Il cuore verde della città sono senz’altro i Giardini Pubblici con il loro sapore liberty ed esotico. Il più grande e monumentale è invece il Parco Teodorico, ideale per corse e passeggiate. Giardino Rasponi è un delizioso salotto all’aperto, mentre il Parco della Pace è un inno all’arte, popolato da monumentali mosaici moderni. In zona Darsena si trova la multiforme Rocca Brancaleone: un po’ giardino, un po’ dehor, un po’ cinema e teatro all’aperto. Adoro passeggiare immersa nella natura!"],

    # Trasporti
    r'(.*)(ztl|ZTL|[Zz]ona(.*)[Tt]raffico [Ll]imitato)(.*)\??':["Il centro storico di Ravenna è in gran parte chiuso al traffico mediante l’impiego di Zone a Traffico Limitato. L’ingresso non autorizzato in queste aree comporta una sanzione. Le zone in questione sono: \n> 24h \n1. Via Di Roma; 2. Via Guaccimanni; 3. Via Baccarini; 4. Via Rondinelli; Via Guerrini; 5. Via Cavour (ingresso piazzetta Gandhi); 6. Via Ponte Marino \n> Dalle 7.30 alle 20.30 \n1. Via Mariani; 2. Via Guerrini; 3. Via Matteucci \nPer evitare la multa: \n- Puoi lasciare la macchina in un parcheggio fuori dalla Zona a Traffico Limitato; \n- Puoi chiedere informazioni al tuo albergatore, se la tua struttura ricettiva in cui soggiorni si trova all’interno del centro storico. Lui può godere di un’autorizzazione speciale che può condividere con te e tutti i suoi clienti; \n- Puoi acquistare un contrassegno giornaliero per la circolazione e sosta all’interno della Zona a Traffico Limitato; \n- Se sei titolare di un contrassegno per invalidi (oppure stai accompagnando una persona titolare di un contrassegno invalidi), puoi accedere liberamente all’interno della ZTL (previa comunicazione a sirio@comune.ra.it ).\nPosso rispondere a qualche altra domanda? "],
    r'(.*)[Tt]axi(.*)\??':["La Cooperativa Ravenna Uno (Radio Taxi) è un consorzio di 21 tassisti che fa parte del Comune di Ravenna. Opera 365 giorni all'anno, 24 ore su 24, inclusi i giorni festivi. Per il servizio notturno (dalle 24.00 alle 7.00) è gradita la prenotazione. \nLe stazioni di sosta si trovano: alla Stazione Ferroviaria in Piazza Farini, in Piazza Garibaldi, all'Ospedale Civile Santa Maria delle Croci in Via Missiroli. \nTelefono: 0544 33888 \nEmail: radiotaxi.ra@gmail.com \nTi posso dare qualche altra informazione su Ravenna?"],
    r'(.*)([Mm]etropolitana|metro|mezzi sotterranei)(.*)\??':["Ravenna non è servita di un sistema metropolitano. La città dispone comunque di un sistema funzionante e ben servito di mezzi pubblici, tra cui autobus, biciclette e monopattini elettrici. \nC'è altro che vuoi sapere?"],
    r'(.*)((app|applicazione)(.*)(trasporto pubblico|trasporti|mezzi|mezzi pubblici)|(trasporto pubblico|trasporti|mezzi|mezzi pubblici)(.*)(app|applicazione))(.*)\??':["La città purtroppo non è dotata di un app per i mezzi pubblici. \nC'è altro che vuoi sapere?"],
    r'(.*)(bigliett[oi])(.*)(trasporto pubblico|trasporti|mezzi|mezzi pubblici)(.*)\??':["Il sistema di trasporto offre la possibilità di acquistare biglietti giornalieri, carnet e pass speciali per  i turisti. Questi possono essere acquistati nelle edicole e tabaccherie della città, direttamente sui mezzi di trasporto oppure online sul sito di StartRomagna. \nLe tariffe dei vari pacchetti variano a seconda del numero di zone che si attraversano durante il viaggio. Scegli la modalità di viaggio che più si addice alle tue esigenze a questo link https://www.startromagna.it/titoli-di-viaggio-ravenna/ \nInoltre, se sei interessato a scoprire altre province della Romagna, esiste il Romagna Smart Pass, un biglietto che ti permette di girare nelle tre zone di Ravenna, Forlì-Cesena e Rimini. Per maggiori informazioni clicca questo link https://www.startromagna.it/turismo/romagna-smart-pass/"],
    r'(.*)parchegg.*\??':["Il centro storico di Ravenna è servito da numerosi parcheggi liberi e a pagamento. Quando si transita per il centro occorre però prestare attenzione alle Zone a Traffico Limitato. \nPer ulteriori informazioni relative a sosta gratuita, parcheggi scambiatori, parcheggi a pagamento e autorimesse cliccare il seguente link   https://www.turismo.ra.it/muoversi-ravenna/parcheggi-ravenna/ \nTi posso dare qualche altra informazione su Ravenna?"],
    r'(.*)(noleggi|servizio|affitt).*(biciclette|bici)(.*)':["Il territorio ravennate è in pianura ed è collegato da una fitta rete di piste ciclabili. Le principali strutture ricettive della città offrono quasi sempre un servizio di prestito biciclette, ma se questo non dovesse avvenire puoi usufruire dei servizi di bike sharing e il nuovo servizio di monopattini elettrici dislocati in città."],
    r'(.*)(ferrovia|stazione)(.*)\??':["La città di Ravenna è munita della stazione, dalla quale transitano anche treni ad alta velocità. Si trova in Piazza Carlo Luigi Farini e dista 10 minuti a piedi dalla piazza principale. \nPer maggiori informazioni sull’accessibilità, sui servizi presenti e per rimanere aggiornato sui treni in arrivo e partenza in questa stazione clicca il link https://www.rfi.it/it/stazioni/ravenna.html \nTi posso dare qualche altra informazione su Ravenna?"],

    # Bambini
    r'(.*)(bambin|ragazz)(.*)\??':["Per percorsi, itinerari e visite della città e dei dintorni dedicati ai bambini cliccare questo link \n https://www.travelemiliaromagna.it/cosa-fare-bambini-ravenna/ \nC'è altro che vuoi sapere? "],
    
    # Cibi e prodotti tipici
    r'(.*)(si beve|bere|bevand|vin)(.*)\??':["In Romagna circola una piacevole storiella, secondo la quale è possibile riconoscere il confine fra l’Emilia e la Romagna semplicemente chiedendo da bere. Se alla richiesta viene offerto un bicchiere d’acqua, si è senza dubbio in Emilia; ma se viene offerto del vino, allora significa che ci si trova in Romagna! \nI vini più pregiati prodotti in questa terra sono il Sangiovese, la Cagnina, il Trebbiano, l’Albana e il Pagadebit.\nTi posso dare qualche altra informazione su Ravenna?"],
    r'([dD]ove(.*)(trov|mang|assagg|prov)(.*)(prodott|cib|aliment|cos|tipic|caratteristic)(.*)\??|(.*)(ristorant|pranz|cena)(.*)\??|[Dd]ove(.*)mang(.*)\??)':["Il centro città è pieno di ristoranti e locali in cui fermarsi ed assaggiare piatti e prodotti tipici di Ravenna. Ti consiglio anche di passare al mercato coperto, in piazza Andrea Costa, dove potrai girare tra botteghe e locali in cui acquistare o assaggiare tutto quello che la città ha da offrire.\nPosso esserti utile in qualche altro modo?"],
    r'((.*)(prodott|cib|aliment|piatt)(.*)(tipic|caratteristic)(.*)\??|(.*)(mang|assag)(.*)\??)':["La città di Ravenna offre numerose prelibatezze. Partendo dai primi, immancabili sono i cappelletti in brodo o al ragù, i passatelli, la Spoja lorda (un tipo di pasta ripiena all'uovo di forma quadrata), gli strozzapreti e i garganelli (un formato di pasta all'uovo realizzata a mano, di forma tubolare). \nPassando per i secondi non si possono non assaggiare la piadina e i crescioni, il formaggio squacquerone, le cozze di Marina di Ravenna e per gli amanti della carne la braciola di castrato. \nInfine, un pasto non può dirsi concluso senza il dolce! La Zuppa inglese e la ciambella romagnola coroneranno il vostro banchetto. \nVuoi sapere qualcos'altro della mia città?"],

    # Mappa e alloggi
    r'(.*)(mappa|carta|cartina)(.*)(citt[àa]|[Rr]avenna|territorio)(.*)\??':["Cliccando questo link è possibile visualizzare una mappa della città di Ravenna in cui sono inclusi i principali luoghi di interesse, aree verdi e servizi \nhttps://www.turismo.ra.it/wp-content/uploads/2021/02/mappa_ravenna_ita.pdf \nTi posso dare qualche altra informazione su Ravenna?"],
    r'(.*)(allogg|hotel|alberg|B&B|b&b|pension|dormire|soggiornare|alloggiare)(.*)\??':["In città ci sono numerosi hotel, alberghi e B&B pronti ad accoglierti! Ti consiglio di visitare i principali siti di comparazione per scoprire le offerte migliori e i servizi disponibili.\nPosso rispondere a qualche altra domanda?"],

    # Tour, visite guidate e percorsi
    r'([cC]osa(.*)(fare|ved|visit)(.*)(un giorno|1 giorno)(.*)\??|(.*)tour(.*)(un giorno|1 giorno)(.*)\??)':["Ravenna è una città ricca di storia e cultura. Se la si vuole visitare in un giorno solo occorre scegliere un percorso da seguire per non perdersi tra le sue numerose bellezze. \nSi potrebbe privilegiare la visita ai monumenti UNESCO, ovvero Il Mausoleo di Galla Placidia, il Battistero Neoniano (o degli Ortodossi), il Battistero degli Ariani, la Basilica di Sant’Apollinare nuovo, la Cappella Arcivescovile o di Sant’Andrea, il Mausoleo di Teodorico, San Vitale e Sant’Apollinare in Classe. \nUn’altra possibile scelta è quella di optare per il percorso Dantesco, seguendo la storia del poeta e scoprendo il suo rapporto con la città. \nVuoi sapere qualcos'altro della mia città?"],
    r'([Cc]osa(.*)(fare|ved|visit)(.*)(due giorni|2 giorni|fine settimana|weekend)(.*)\??|(.*)tour(.*)(due giorni|2 giorni|fine settimana|weekend)(.*)\??)':["Otto monumenti UNESCO testimoniano la grandezza e l’importanza della città durante il tempo: Il Mausoleo di Galla Placidia, il Battistero Neoniano (o degli Ortodossi), il Battistero degli Ariani, la Basilica di Sant’Apollinare nuovo, la Cappella Arcivescovile o di Sant’Andrea, il Mausoleo di Teodorico, San Vitale e Sant’Apollinare in Classe. \nImperdibile è inoltre la Domus dei Tappeti di Pietra, uno dei più importanti siti archeologici italiani scoperti negli ultimi decenni, costituita da 14 ambienti pavimentati con mosaici policromi e marmi appartenenti ad un edificio privato bizantino del V-VI secolo. \nNon si può poi passare da Ravenna senza visitare la tomba di Dante e il percorso a lui dedicato. \nPoco fuori Ravenna, infine, si trova Classe, antica sede della flotta imperiale romana, nella quale si possono osservare le antiche rovine dell’insediamento e del porto della città. "],
    r'(.*)[Qq]uant(.*)(giorni|tempo)(.*)(citt[aà]|[Rr]avenna)\??':["Ravenna è una splendida città ricca di storia ma dalle dimensioni modeste. Un paio di giorni dovrrebbero bastare per poterla esplorare a fondo."],
    r'(.*)(guida)(.*)\??':["Vuoi visitare Ravenna accompagnato da chi ne conosce tutti i segreti e le bellezze? Trova la guida o l’accompagnatore turistico che possono fare al caso tuo a questo link https://www.turismo.ra.it/visite-guidate/ \nC'è altro che vuoi sapere?"],

    # Monumenti, musei, chiese e mosaici
    r'(([Dd]ove|[Qq]ual|[Cc]os)(.*)(vedere|ammirare|osservare)(.*)([Dd]ant)(.*)\??|(.*)(percorso [Dd]antesco|zona del silenzio)(.*)\??)':["A Ravenna si parla di Zona del silenzio riferendosi a quella porzione di centro storico posta attorno alla Tomba di Dante, un tempietto neoclassico progettato da Camillo Morigia nel 1780-1782 per ospitare le spoglie mortali di Dante Alighieri. \nQuest’area comprende – oltre alla tomba del sommo poeta – il Quadrarco di Braccioforte, gli Antichi Chiostri Francescani, il Museo Dante e la vicina Basilica di San Francesco. \nSe ti interessa questo argomento, prova a consultare questo link: https://www.turismo.ra.it/cultura-e-storia/luoghi-della-memoria/tomba-dante-alighieri \nPosso aiutarti in qualche altro modo?"],
    r'(.*)(citt[àa] sotterranea|[nN]ecropoli|catacomb)(.*)\??':["La città di Ravenna non possiede una parte sotterranea da visitare. Ci piace stare all’aria aperta!\nPosso aiutarti in qualche altro modo?"],
    r'(.*)(bigliett)(.*)(monument|chies|[gG]alla|[Bb]attistero|[Bb]asilica|[Cc]appella|[Vv]itale|[Aa]pollinare|[uU]nesco|UNESCO)(.*)\??':["L’accesso ai monumenti è consentito da un biglietto unitario dal prezzo di €10,50, che permette la visita della Basilica di San Vitale, della Basilica di Sant’Apollinare Nuovo e del Museo Arcivescovile. Con un supplemento di €2 è inoltre possibile l’ingresso al Mausoleo di Galla Placidia e al Battistero Neoniano. \nI biglietti si possono acquistare presso le biglietterie ufficiali collocate presso la Basilica di Sant’Apollinare Nuovo, in via di Roma 53 o al Museo Arcivescovile, in piazza Arcivescovado 1. \nE’ inoltre possibile acquistare i biglietti online a questo link https://www.ravennamosaici.it/orari-e-prezzi/?_gl=1*7oxa09*_up*MQ..*_ga*MTIzMzYxNzY5Ni4xNzE2OTY4OTAy*_ga_NXY7LP33MX*MTcxNjk2ODkwMi4xLjAuMTcxNjk2ODkwMi4wLjAuMA..&gclid=Cj0KCQjwpNuyBhCuARIsANJqL9OKH-4Xd5oc4lTnQqI8c4WIqB9pnD_Dv_c0att-whJ9cMyntubcB5saAmbQEALw_wcB/#biglietteria \nPosso aiutarti in qualche altro modo?"],
    r'(.*)(scont|riduzion)(.*)(bigliett|universit|ragazz|giovan|anzian|bambin|grupp|disabil)(.*)\??':["L’ingresso ai monumenti presenta uno sconto per queste categorie: \nIngresso ridotto: gruppi (minimo 20 paganti). \nIngresso gratuito: bambini di età inferiore ai 10 anni; persone con disabilità certificata, possessori della disability card o carta bianca; residenti del Comune di Ravenna; religiosi/e; militari; guide turistiche abilitate nell’esercizio della propria attività professionale o per formazione; insegnanti accompagnatori di gite scolastiche (1 gratuità ogni 10 studenti)."],
    r'(.*)(orar|apertura|apr|chiu[ds])(.*)(chies|monument|[gG]alla|[Bb]attistero|[Bb]asilica|[Cc]appella|[Vv]itale|[Aa]pollinare|[uU]nesco|UNESCO)(.*)\??':["È possibile scoprire l’orario di apertura e di chiusura dei monumenti e delle biglietterie a questo link https://www.ravennamosaici.it/orari-e-prezzi/?_gl=1*7oxa09*_up*MQ..*_ga*MTIzMzYxNzY5Ni4xNzE2OTY4OTAy*_ga_NXY7LP33MX*MTcxNjk2ODkwMi4xLjAuMTcxNjk2ODkwMi4wLjAuMA..&gclid=Cj0KCQjwpNuyBhCuARIsANJqL9OKH-4Xd5oc4lTnQqI8c4WIqB9pnD_Dv_c0att-whJ9cMyntubcB5saAmbQEALw_wcB/#biglietteria"],
    r'(.*)(museo|musei)(.*)\??':["Ravenna è una città d’arte e cultura, potrete visitare moltissimi musei: la Domus dei Tappeti di Pietra, il Museo Tamo Mosaico, la Cripta Rasponi e i Giardini pensili, il MAR – Museo d’Arte della città di Ravenna, il Museo Nazionale, il Museo Dante e il Museo Classis Ravenna. \nPer maggiori informazioni sugli orari e sui prezzi dei biglietti consultare questo link https://www.turismo.ra.it/cultura-e-storia/musei-biblioteche/"],
    r'(.*)(piazza|piazza principale|piazza pi[ùu] grande)(.*)\??':["La piazza principale della città è Piazza del popolo. Da più di sette secoli è sede dei principali palazzi del potere (quello del Comune e quello della Prefettura, un tempo della Legazione Pontificia), insostituibile luogo di appuntamento e di ritrovo per tutti i cittadini.\nC'è altro che vuoi sapere?"],
    r'((.*)(mostra|mostre|esposizion)(.*)(é|sono|visit|ved|sar[aà])(.*)\??|(.*)(é|sono|visit|ved|sar[aà])(.*)(mostra|mostre|esposizion)(.*)\??)':["La città è molto viva e ospita svariate mostre, anche temporanee. Prova a consultare questo link per saperne di più https://www.finestresullarte.info/citta/ravenna \nPosso rispondere a qualche altra domanda?"],
    r'(.*)(vedere|visitare|esplorare)(.*)(fuori [Rr]avenna|fuori di [Rr]avenna|fuori da [Rr]avenna|vicinanze|vicino a|dintorni|paes[ei] limitrof[ei]|campagn[ae]|fuoriporta|fuori porta)(.*)\??': ["Se hai la possibilità di soggiornare a Ravenna per qualche giorno non puoi non fare un giro nei paesi limitrofi, ricchi di storia e tradizioni. A questo link troverai qualche spunto per una gita fuoriporta https://www.turismo.ra.it/myravenna/citta-arte/5-idee-gita-dintorni-ravenna"],
    r'(.*)(piazze|mura|porte|torr[ei]|citt[aà] fortificata)(.*)\??':["Una città fortificata, con bastioni e mura massicce, torri e piazzeforti. Di questo passato medievale e risorgimentale resistono una decina di porte e molte piazze storiche. \nPer maggiori informazioni sulla storia delle singole piazze e porte consulta questo link \nhttps://www.turismo.ra.it/cultura-e-storia/piazze-porte/ \nPosso aiutarti in qualche altro modo?"],
    r'(.*)(monumenti|attrazioni)(.*)\??': ["Otto monumenti UNESCO testimoniano la grandezza e l’importanza della mia città durante il tempo: \nIl Mausoleo di Galla Placidia, il Battistero Neoniano (o degli Ortodossi), il Battistero degli Ariani, la Basilica di Sant’Apollinare nuovo (dove potrete trovare anche me!), la Cappella Arcivescovile o di Sant’Andrea, il Mausoleo di Teodorico, San Vitale e Sant’Apollinare in Classe. \nImperdibile è inoltre la Domus dei Tappeti di Pietra, uno dei più importanti siti archeologici italiani scoperti negli ultimi decenni, costituita da 14 ambienti pavimentati con mosaici policromi e marmi appartenenti ad un edificio privato bizantino del V-VI secolo. \nNon si può poi passare da Ravenna senza visitare la tomba di Dante e il percorso a lui dedicato. \nPoco fuori Ravenna, infine, si trova Classe, antica sede della flotta imperiale romana, nella quale si possono osservare le antiche rovine dell’insediamento e del porto della città. "],
    r'[Dd]ove(.*)(mosaic[oi])(.*)\??':["I mosaici sono un simbolo di questa città e si possono ammirare nelle principali chiese e monumenti. Inoltre, per le strade si possono scovare cartelli o opere di artisti contemporanei che fanno utilizzo della storica arte del mosaico, a testimonianza di quanto questa tecnica sia un simbolo cittadino. \nC'è altro che vuoi sapere?"],
    r'(.*)[Gg]alla(.*)\??':["Considerato da molti come uno dei tesori più preziosi della città, posto alle spalle della basilica di San Vitale, il Mausoleo di Galla Placidia è uno degli edifici più antichi di Ravenna, dichiarato patrimonio dell’Umanità dall’Unesco nel 1996. \nCommissionato nella prima metà del V secolo d.C. (dopo il 426 d.C.) dall’imperatrice Galla Placidia, figlia di Teodosio e sorella dell’imperatore Onorio, nonché imperatrice reggente per conto del figlio Valentiniano III, questo piccolo mausoleo doveva servire come sua “ultima dimora” in cui essere seppellita assieme al fratello e al marito Costanzo III, sposato in seconde nozze.\nNon fu però mai utilizzato in tal senso: nel 450 d.C. la donna morì difatti a Roma e qui venne seppellita. \nA cavallo tra la tradizione artistica ellenistico-romana e quella cristiana, i temi iconografici rappresentati sviluppano, a più livelli interpretativi, il tema della vittoria della vita eterna sulla morte. \nAl centro della cupola, in un immenso cielo stellato, appare in tutto il suo splendore una croce latina dorata, simbolo di Cristo Sole Nascente. Nelle lunette, invece, gli apostoli contornati da colombe e zampilli d’acqua, a simboleggiare la Grazia che attinge alla Fonte Divina. \nInteressante vero? Vuoi chiedermi qualcos’altro?"],
    r'(.*)[bB]attistero(.*)([Nn]eoniano|[oO]rtodossi)\??':["Posto a lato dell’attuale Duomo di Ravenna, il Battistero Neoniano (o degli ortodossi) è uno dei monumenti più antichi di Ravenna, nonché parte integrante del circuito cittadino degli edifici paleocristiani dichiarati Patrimonio dell’Umanità dall’UNESCO nel 1996. \nTra tutti i battisteri realizzati tra il IV e V secolo nel Mondo antico Occidentale ed Orientale (Antiochia, Costantinopoli, Efeso, Treviri, Milano, Aquileia e Roma), questo edificio si caratterizza per essere il meglio conservato dal punto di vista architettonico e decorativo. \nCosì come in quella del Mausoleo di Galla Placidia, anche qui la decorazione appare straordinariamente ricca e luminosa, quasi a richiamare il passaggio dall’ombra alla luce, grazie al rito del battesimo. \nAl centro della cupola un grande medaglione racchiude la scena del Cristo, raffigurato immerso sino alla vita nelle acque trasparenti del fiume Giordano in compagnia di San Giovanni Battista: a oggi costituisce la più antica testimonianza di una scena del battesimo del Salvatore eseguita a mosaico in un edificio monumentale. \nAl centro dell’edificio, una vasca ottagonale di marmo greco e porfido, rifatta nel 1500, conserva ancora qualche frammento originale del V secolo. \nCos’altro posso raccontarti?"],
    r'(.*)[bB]attistero(.*)([Aa]riani)\??':["Poco lontano dalla stazione ferroviaria di Ravenna si affaccia il Battistero degli Ariani, uno degli otto monumenti dichiarati Patrimonio dell’Umanità dall’UNESCO nel 1996. \nFatto innalzare presumibilmente da Teodorico alla fine del V secolo d.C., quando l’arianesimo era religione ufficiale della corte, doveva apparire come complemento liturgico alla vicina Cattedrale degli Ariani. \nA metà del VI secolo il battistero fu riconsacrato per volere di Giustiniano al culto ortodosso, divenendo un oratorio dedicato alla Vergine Maria. \nAl suo interno nulla è rimasto degli stucchi e degli ornamenti che sicuramente rivestivano le pareti. L’unica parte conservata è la cupola rivestita di mosaici raffiguranti il battesimo del Cristo, un’iconografia già presente nel Battistero Neoniano. \nPur conservando la medesima impostazione iconografica di quest’ultimo, da cui trae ispirazione, il mosaico del Battistero degli Ariani testimonia il culto della corte di Teodorico, fondato sulla figura di Cristo al contempo divina e terrena. \nC’è qualcos’altro che vuoi sapere?"],
    r'(.*)[Ss]an(.*)[Vv]itale(.*)\??':["Nel cuore della città, a pochi passi da alcuni dei monumenti più suggestivi del centro storico, si erge maestosa la basilica di San Vitale. \nTestimone della grandezza dell’impero bizantino, l’edificio spicca per la raffinatezza e la preziosità delle sue decorazioni e dei materiali impiegati. \nCommissionata sotto il dominio dei Goti al tempo dell’arcivescovo Ecclesio (525-526 d.C.), la basilica fu terminata quasi vent’anni dopo durante il regno dell’imperatore Giustiniano. \nLa basilica presenta un impianto planimetrico centrale e soluzioni strutturali che la distinguono nettamente dalle tipiche chiese d’impianto basilicale. \nOltre alla cupola affrescata secondo il gusto barocco e il labirinto della pavimentazione, a rendere mozzafiato l’interno della basilica sono i mosaici bizantini che decorano l’abside. \nTra gli innumerevoli dettagli che rendono unica questa decorazione musiva spiccano le celebri rappresentazioni dei cortei di Teodora e Giustiniano, collocati nella parte inferiore delle pareti, uno di fronte all’altro. \nInteressante vero? Vuoi chiedermi qualcos’altro?"],
    r'(.*)[Ii]n [Cc]lasse(.*)\??':["Alle porte del piccolo centro abitato di Classe, a circa 8 km a sud di Ravenna, si erge uno degli otto monumenti che compongono il sito Unesco della città: è la grandiosa e solenne Basilica di Sant’Apollinare in Classe con il suo caratteristico campanile cilindrico, dichiarata Patrimonio dell’Umanità dall’UNESCO nel 1996. \nNata per accogliere le spoglie di Apollinare, Santo patrono della città, la basilica fu edificata su una precedente area cimiteriale in uso tra la fine del II e l’inizio III secolo d.C. dove sembra avesse trovato sepoltura lo stesso protovescovo. \nImponente e maestosa, è stata definita il più grande esempio di basilica paleocristiana oggi conosciuta. \nNonostante le spoliazioni subite nel corso dei secoli (in origine era preceduta da un quadriportico poi andato distrutto), la chiesa tutt’oggi preserva la bellezza della struttura originaria ed è ammirata per gli splendidi mosaici policromi del suo catino absidale e gli antichi sarcofagi marmorei degli arcivescovi collocati lungo le navate laterali."],
    r'(.*)[Aa]pollinare(.*)[Nn]uovo(.*)\??':["La basilica fu fatta erigere dal re goto Teodorico nel 505 come chiesa di culto ariano. \nIn seguito alla conquista della città da parte dell'Impero bizantino, la basilica fu consacrata al culto ortodosso. \nSecondo la tradizione, nel IX secolo d.C. le reliquie di Sant’Apollinare furono qui traslate dalla Basilica di Classe, e proprio in quell’occasione l’edificio ricevette la sua intitolazione a Sant’Apollinare, detta “Nuovo”. \nAll’interno si ritrova uno dei cicli in mosaico d’età paleocristiana e tardoantica più famosi al mondo. Una straordinaria decorazione in mosaici percorre tutta la navata centrale. \nLe 26 scene cristologiche, risalenti appunto al periodo di Teoderico, rappresentano infatti il più grande ciclo monumentale del Nuovo Testamento e, fra quelli realizzati a mosaico, il più antico giunto fino a noi."],
    r'(.*)[Aa]pollinare(.*)\??':["A quale delle due chiese ti riferisci? Sant'Apollinare Nuovo o Sant'Apollinare in classe?"],
    r'(.*)[Mm]ausoleo(.*)[Tt]eodorico(.*)\??':["Lasciato il centro storico e oltrepassata la linea ferroviaria, si erge in un grande parco uno dei monumenti più iconici di tutta Ravenna. \nÈ il Mausoleo di Teodorico, la più celebre e importante costruzione funeraria realizzata dagli Ostrogoti in Italia, inserita dall’Unesco nella lista dei siti italiani Patrimonio dell’Umanità. \nFatto costruire per volontà di Teodorico come luogo per la propria sepoltura attorno al 520 d.C., il monumento mescola sapientemente ad alcune influenze orientali la tradizione costruttiva romana, dando vita un monumento crocevia tra l’antico popolo romano e quello dei goti “invasori”. \nInteramente realizzato in blocchi di pietra d’Aurisina messi in posa a secco, l’edificio si sviluppa su pianta centrale, articolandosi in due ordini sovrapposti, entrambi decagonali. \nA ricoprire tutto una grande cupola monolitica dalle misure sorprendenti, senza eguali nel patrimonio architettonico antico e moderno (10,76 m di diametro e 3,09 m di altezza), coronata da dodici anse con le iscrizioni dei nomi di otto Apostoli e quattro Evangelisti. \nLe spoglie di Teodorico, qui probabilmente custodite, furono rimosse e disperse durante il dominio bizantino quando, a seguito dell’editto di Giustiniano del 561 d.C., il mausoleo fu trasformato in oratorio e consacrato al culto ortodosso. \nTi interessa sapere qualcos’atro?"],
    r'(.*)[Cc]appella(.*)[Aa]rcivescovile(.*)|(.*)[Cc]hiesa(.*)[Aa]ndrea\??':["La cappella arcivescovile o di Sant’Andrea si trova al primo piano del Museo Arcivescovile di Ravenna, ed è stata dichiarata Patrimonio dell’Umanità dall’UNESCO nel 1996. \nCostruita agli inizi del V secolo d.C. su volere del vescovo Pietro II, è l’unico monumento ortodosso ancora esistente in città realizzato ai tempi di Teodorico come oratorio privato al servizio dei vescovi cattolici. \nA seguito della conquista della città da parte dei bizantini, la cappella fu dedicata a Sant’Andrea, le cui reliquie arrivarono a Ravenna da Costantinopoli attorno alla metà del VI secolo. \nTutto il programma decorativo della cappella è un inno al Salvatore, a cui l’edificio è dedicato, in un’interpretazione chiaramente anti-ariana. \nLa presenza del Cristo in veste di guerriero, la croce sulla spalla, il monogramma e il volto dominano in vari punti dell’apparato confermando l’interpretazione iconografica. \nPosso raccontarti qualcosa di nuovo?"],
    r'(.*)[Dd]omus(.*)\??':["La Domus dei Tappeti di Pietra è uno dei più importanti siti archeologici italiani scoperti negli ultimi decenni. \nCollocata all'interno della settecentesca Chiesa di Santa Eufemia, in un vasto ambiente sotterraneo situato a circa tre metri sotto il livello stradale, è costituita da 14 ambienti pavimentati con mosaici policromi e marmi appartenenti ad un edificiio privato bizantino. \nPer maggiori informazioni sugli orari di apertura e sui biglietti consultare questo link \nhttps://domusdeitappetidipietra.it/"],
    
    # Servizi e attrazionis
    r'(.*)([aA]cquario)(.*)\??':["A Ravenna non è presente un acquario cittadino. La città e le zone limitrofe offrono numerose alternative per ammirare la flora e la fauna del luogo."],
    r'(.*)([Zz]oo)(.*)\??':["A 10 kilometri da Ravenna si può trovare SafariRavenna, un parco faunistico contenente più di 100 specie diverse di animali. \nTi ricordo tuttavia che si tratta di animali in cattività che non si trovano nel loro habitat naturale. \nLa città e le zone limitrofe offrono numerose alternative per ammirare la flora e la fauna del luogo. "],
    r'(.*)([oO]rto [Bb]otanico)(.*)\??':["Il Giardino Rasponi (o delle Erbe Dimenticate) è un delizioso angolo verde del centro di Ravenna, posto all’ombra della cupola del Duomo e del Battistero Neoniano, all’incrocio tra Via Rasponi e Via Guerrini. \nTra erbe aromatiche e una piccola bottega-bistrot all’aperto, questo spazio rappresenta un romantico scrigno di pace e bellezza dove storia e natura si incontrano per offrire ai ravennati e ai turisti una meta alternativa alle loro passeggiate."],
    r'(.*)(orar)(.*)(mess)(.*)\??':["La città di Ravenna conta numerosissime chiese. Cerca quella più vicino a te e scopri l’orario delle messe con l’applicazione DinDonDan! \nPosso esserti utile in qualche altro modo?"],
    r'(.*)(fontan)(.*)\??':["A questo link puoi trovare la mappa delle fontanelle presenti in città https://www.fontanelle.org/Mappa-Fontanelle-Ravenna-Emilia-Romagna.aspx \nPosso esserti utile in qualche altro modo?"],
    r'(.*)(teatr)(.*)\??':["Il Teatro Dante Alighieri è il maggiore teatro della città di Ravenna e uno dei più eleganti teatri storici d’Italia. L’edificio neoclassico è dotato di circa 850 posti fra platea e palchi, una volta affrescata e un’elegante sala del ridotto. Si trova in via Angelo Mariani 2. \nPer maggiori informazioni sulla stagione teatrale e sugli spettacoli consultare il seguente link \nhttps://www.teatroalighieri.org/spettacoli/ \nPosso esserti utile in qualche altro modo?"],
    r'(.*)(bibliotec)(.*)\??':["La città di Ravenna ospita una tra le venti istituzioni librarie più grandi e importanti d’Italia, ovvero la biblioteca Classense. La struttura ospita una vasta raccolta di volumi appartenenti a varie tipologie documentarie: circa 800.000 opere a stampa, antiche e moderne, manoscritti, incisioni, mappe, fotografie, documenti d’archivio e materiale multimediale. Tra questi troviamo la preziosa raccolta dei testi del Canzoniere e dei Trionfi di Petrarca (Codice Ravennate 429), che contiene anche un originale del pittore Sandro Botticelli, e l’unico manoscritto al mondo che contenga le 11 commedie di Aristofane. Adoro passare il tempo immerso nel silenzio e la cultura di questo luogo! \nOggi la biblioteca è uno spazio dinamico aperto al pubblico, punto di riferimento per studenti e studiosi. Durante l’anno vengono infatti programmati moltissimi incontri, conferenze tematiche ma anche mostre d’arte e libraie con approfondimenti didattici e divulgativi. \nSi trova in via Alfredo Baccarini 3. \nPosso aiutarti in qualche altro modo?"],
    r'(.*)(bagno pubblico|bagni pubblici)(.*)\??':["La città dispone di numerosi bagni pubblici sparsi su tutto il territorio. Trova il bagno più vicino a te cliccando questo link https://www.azimut-spa.it/ita/Servizi/Servizi-igienici\nPosso rispondere a qualche altra domanda?"],
    r'(.*)(universit[aà])(.*)\??':["La città è sede del Campus di Ravenna, distaccamento dell’Alma Mater Studiorum, università bolognese. \nLe strutture sono visitabili e aperte al pubblico. "],
    r'(.*)(pronto soccorso|guardia medica)(.*)\??':["Il pronto soccorso di Ravenna di trova in Viale Randi n 5. \nParcheggio: Viale Randi: gratuito con un settore a pagamento; Via Missiroli e vie adiacenti: a pagamento; Piazza Vacchi e Piazza Resistenza: gratuito \nLa guardia medica non è presente in città, la più vicina si trova a Lugo."],
    r'(.*)(stadio)(.*)\??':["Ravenna ospita lo stadio comunale intitolato a Bruno Benelli. Qui gioca la squadra della città, il Ravenna football club 1913, che milita in serie D. \nLo stadio si trova in via Punta Stilo 29. Forza Ravenna!"],
    r'(.*)(infopoint|(ufficio|uffici) del turismo)(.*)\??':["Ravenna offre numerosi uffici di informazione turistica. Trova quello più vicino a te cliccando il seguente link \nhttps://www.turismo.ra.it/servizi-utili/uffici-informazione-turistica/"],
    r'((.*)(vita notturna|movida)(.*)\??|[Dd]ove(.*)(andare|uscire)(.*)(sera|notte|vita notturna|movida)(.*)\??|[Cc]osa(.*)fare(.*)(sera|notte|vita notturna|movida)(.*)\??)':["Ravenna è una piccola città dalla movida rilassata. La maggior parte delle attività e locali come ristoranti, pub, enoteche e caffetterie si trovano nel centro storico. \nDurante il periodo estivo non mancano però eventi che la animano e la valorizzano. Nei mesi di giugno e luglio si può assistere al Ravenna Festival, manifestazione in cui si esibiscono artisti e direttori d’orchestra di fama mondiale. \nDa luglio a fine agosto invece, si svolge il “Mosaico di Notte”, occasione che permette di visitare monumenti e musei fino a tarda sera. \nPer chi è alla ricerca del divertimento più mondano e sfrenato, a Marina di Ravenna si concentrano i locali notturni più famosi. Qui si respira tutta l’aria della riviera romagnola e la sua allegria.\nVuoi sapere qualcos'altro della mia città?"],
    r'((.*)(negoz|shop)(.*)(souvenir|suvenir)(.*)\??|[Dd]ove(.*)(souvenir|suvenir)(.*)\??|[Dd]ove(.*)(compr|acquist)(.*)(tipic|caratteristic)(.*)\??)':["Gli shop ufficiali presenti in città si possono consultare a questo link: \nhttps://www.ravennamosaici.it/shop-negozi/  \nScopri quello più vicino a te!\nPosso rispondere a qualche altra domanda?"],
    r'(([Cc]osa|[Qq]ual|[Cc]he)(.*)(souvenir|suvenir)(.*)\??|[Cc]os(.*)(tipic|caratteristic)(.*)(compr|trov)(.*)\??|[Cc]os(.*)(compr|trov)(.*)(tipic|caratteristic)(.*)\??)':["Nello shop https://www.ravennamosaici.it/shop-negozi/ si possono trovare libri, mosaici, gadget a tema Dante e molto altro ancora. \nUn’altra scelta possibile è quella di acquistare prodotti tipici della zona. Corri al mercato coperto della città per scoprire le prelibatezze che offrono le botteghe ravennati!\nC'è altro che vuoi sapere?"],
    r'(.*)(mapp)(.*)(musei|monumenti|siti d\'interesse|siti storici|chiese|[uU]nesco|UNESCO)(.*)\??':["E’ possibile consultare una mappa dei principali monumenti ravennati, con annesso un percorso consigliato, al seguente link \nhttps://ravennamosaici.it/wp-content/uploads/2018/12/2019_O-R-Mappa-Turistica.pdf?_gl=1*q908gs*_up*MQ..*_ga*MTI1NTUzOTc4OC4xNzE2NzM5NTI4*_ga_NXY7LP33MX*MTcxNjczOTUyOC4xLjEuMTcxNjczOTU1Ni4wLjAuMA \nPosso esserti utile in qualche altro modo?"],

    # Eventi
    r'(.*)(event[oi] sportiv[oi])(.*)\??':["Numerosi sono gli eventi sportivi ospitati dalla città. Dai un’occhiata alle varie iniziative cliccando questo link https://www.viviromagna.it/eventi-sport"],
    r'(.*)(event[oi] cultural[ei])(.*)\??':["Numerosi sono gli eventi culturali ospitati dalla città. Dai un’occhiata alle varie iniziative cliccando questo link https://ravennaeventi.net/elencoeventi/8/Arte%20e%20Cultura"],
    r'(.*)(event[oi] musical[ei]|concert[oi])(.*)\??':["Numerosi sono gli eventi musicali ospitati dalla città. Dai un’occhiata alle varie iniziative cliccando questi link \nhttps://www.ravennafestival.org/ \nhttps://www.ravennatoday.it/eventi/tipo/concerti/ \nPosso esserti utile in qualche altro modo?"],
    r'(.*)(event[oi]|ricorrenz|fest)(.*)\??':["Numerosi sono gli eventi ospitati dalla città. Dai un’occhiata alle varie iniziative cliccando questo link https://www.turismo.ra.it/myravenna/citta-arte/eventi-da-non-perdere-ravenna"],
    r'(.*)(apertur[ae] (di sera|seral[ei]|notturn[ae])|event[oi] (di sera|seral[ei]|notturn[oi]))\??':["A partire dal 10 giugno, i commercianti del centro di Ravenna prevederanno aperture serali dei loro negozi ogni lunedì e mercoledì. \nInoltre, nel periodo che va da luglio a fine agosto, si svolgerà il “Mosaico di Notte”, un’occasione che permette di visitare monumenti e musei fino a tarda sera. \nNon perderti queste occasioni!"],

    # Storia
    r'(.*)([Pp]atrono)(.*)\??':["Il patrono di Ravenna è Sant’Apollinare e si festeggia il 23 luglio. \nApollinare conobbe il cristianesimo ad Antiochia di Siria, una delle prime città dove esso si diffuse. Divenne discepolo di Pietro probabilmente intorno al 44. \nLo accompagnò da Antiochia fino a Roma (dove esiste una basilica a lui intitolata) e in seguito fu inviato a Classe, dove la marina militare romana aveva una base. \nSubì il martirio sotto Vespasiano. "],
    r'(.*)subsidenza(.*)\??':["La subsidenza è un lento e progressivo sprofondamento del fondo di un bacino marino o di un'area continentale. Il fenomeno è evidente nelle aree dove l'attiva sedimentazione produce imponenti serie detritiche; ciò è spiegabile solo ammettendo un lento abbassamento del bacino simultaneamente alla deposizione e all'accumulo dei sedimenti. \nLe ipotesi più accreditate per spiegare la subsidenza sono: \n- L'ipotesi isostatica secondo cui il peso stesso, l'assestamento del materiale incoerente, le oscillazioni dei livelli di falda porterebbero allo sprofondamento del substrato; \n- Processi tettonici.\nPosso aiutarti in qualche altro modo?"],
    r'((.*)(storie|leggend[ae])(.*)(citt[aà]|[Rr]avenna)(.*)\??|(.*)(citt[aà]|[Rr]avenna)(.*)(storie|leggend[ae])(.*)\??)':["Numerose sono le storie e le leggende che accompagnano la città di Ravenna. Scopri alcune di queste al link riportato di seguito \nhttps://www.turismo.ra.it/myravenna/stories/curiose-leggende-ravenna \nPosso rispondere a qualche altra domanda?"],
    r'(.*)(negoz|botteg)(.*)(storic|antic)(.*)\??':["Per scoprire le botteghe storiche di Ravenna, con annesse storie e tradizioni, clicca questo link \nhttps://www.turismo.ra.it/myravenna/stories/le-botteghe-storiche-di-ravenna"],
    r'((.*)((person[ae]|personaggi|personaggio|personalità) (famos[ieoa]|celebr[ei]|illustr[ei]))(.*)(omagg|passa|visita|celebra|influenza)(.*)\??|(.*)(omagg|passa|visita|celebra|influenza)(.*)((person[ae]|personaggi|personaggio|personalità) (famos[ieoa]|celebr[ei]|illustr[ei]))(.*)\??)':["Numerose personalità sono passate da Ravenna e sono rimaste incantate dalla sua bellezza, tra queste: \nJorge Luis Borges, George Gordon Byron, Maria Callas, Gabriele D‘Annunzio, Henry James, Gustav Jung, Wassily Kandinsky, Paul Klee, Gustave Klimt, Le Corbusier, Eugenio Montale, Cole Porter, Ezra Pound, Marguerite Youcernar, Oscar Wilde, Herman Hesse. \nPer approfondire meglio il loro legame con la città clicca questo link: \nhttps://www.turismo.ra.it/myravenna/stories/almanacco-personaggi-innamorati-ravenna \nPosso rispondere a qualche altra domanda?\nC'è altro che vuoi sapere?"], 
    r'((.*)(cittadin[ie] famos[ie])(.*)\??|(.*)((person[ae]|personaggi|personaggio|personalità) (famos[ieoa]|celebr[ei]|illustr[ei]|not[aeio]))(.*)\??|(.*)personaggi pi[uù] famosi(.*)\??)':["La città di Ravenna ha dato i natali a numerose personalità illustri, sia di oggi che del passato. Alcuni tra questi sono Amadeus, noto conduttore televisivo, Manuela Benelli, allenatrice ed ex palleggiatrice della nazionale italiana, considerata la più titolata giocatrice di pallavolo della storia italiana o Marco Melandri, pilota e motociclista campione del mondo della classe 250. \nDue celebri personaggi del passato recente sono invece Serafino Ferruzzi, imprenditore italiano, fondatore del gruppo Ferruzzi e Sergio Zavoli che è stato un giornalista, scrittore, politico e conduttore televisivo italiano. \Ripercorrendo la storia della città, tante solo le figure illustri nate o legate a questa terra, come: \n- Francesca Da Rimini: nobildonna ravennate, figlia di Guido da Polenta, signore di Ravenna. Secondo il celebre racconto di Dante Alighieri, unico testimone e narratore sincrono della vicenda, ella s'innamorò del cognato, Paolo Malatesta. Tra i due nacque un amore segreto, che una volta scoperto, portò all’ assassinio dei due amanti. Dante narrerà del loro amore nel V canto dell’inferno, dedicato al girone dei lussuriosi. \n- Giovanni Malpaghini, conosciuto ai suoi tempi anche come Giovanni da Ravenna, è stato un umanista e amanuense italiano. Fu l'amanuense e il segretario personale di Francesco Petrarca.\nPosso esserti utile in qualche altro modo?"],
    r'((.*)(fondat|fondaz)(.*)([Rr]avenna|citt[àa])(.*)\??|(.*)([Rr]avenna|citt[àa])(.*)(fondat|fondaz)(.*))\??':["Le più antiche testimonianze archeologiche rinvenute permettono di datare almeno al V secolo a.C. la presenza degli Umbri nel ravennate dove rimasero indisturbati fino al III secolo a.C. \nGli storici antichi non riuscirono a identificare univocamente l'origine dell'insediamento preromano: per lo storico latino Plinio il Vecchio i fondatori della città sarebbero i Sabini; il greco Strabone invece afferma che i primi insediamenti della zona furono opera dei Tessali mentre per Dionigi di Alicarnasso degli Etruschi; infine, lo storico bizantino Giordane suppone che la zona fosse abitata dai Veneti mentre per Zosimo dai Pelasgi.\nPosso esserti utile in qualche altro modo?"],
    r'(.*)(porto di|[Cc]lasse|archeolog)(.*)\??':["L’insediamento di Classe nasce in età romana, quando Ottaviano Augusto stabilisce a Ravenna la flotta incaricata della difesa del mare Adriatico. Il porto di Classe fu poi collegato al delta del Po dalla fossa Augusta e raggiunse la sua massima espansione tra il II e il III secolo, epoca in cui secondo Cassio Dione il porto poteva contenere fino a 250 navi da guerra mentre la città era abitata da circa 10 000 persone. \nA causa della subsidenza che affligge l'area ravennate, però, il territorio, abbassandosi, divenne progressivamente paludoso. All'inizio del IV secolo, tale fenomeno era così evidente che le banchine, i cantieri e le strade di accesso al porto divennero inservibili. Nel 330 l'imperatore Costantino I decise quindi di trasferire la base della flotta nella nuova capitale dell'impero, Costantinopoli.\nVuoi sapere qualcos'altro della mia città?"],
    r'[Cc]os(.*)(mosaic[oi])(.*)\??':["Il mosaico è una magnifica tecnica decorativa policroma, ottenuta mediante l'utilizzo di frammenti di materiali, nata in Mesopotamia ed esportata nel mondo dell'antichità durante il periodo della dominazione ellenistica e romana. Le tessere, di diversa natura e colore (pietre, vetro, conchiglie), sono decorate con oro e pietre preziose. I mosaici ravennati sono di epoca paleocristiana, databili tra il V e il VI secolo d.C., e sono una delle più grandi meraviglie della mia città. \nC'è altro che vuoi sapere?"],
    r'(.*)[Dd]ante(.*)\??':["Esiliato da Firenze, sua città natale, dopo varie peregrinazioni Dante Alighieri arriva nel 1318 a Ravenna, dove terminò di scrivere la Divina Commedia. La sua permanenza in città fu tuttavia breve, poiché morì nel 1321. \nAncora oggi le sue ossa sono custodite in città, nei pressi della sua tomba, costruita su progetto dell'architetto Camillo Morigia, all’ombra della secolare quercia voluta da Giosuè Carducci. Tutti gli anni, a ridosso della data della sua morte, la città celebra diversi eventi culturali per ricordare il sommo poeta e promuovere la sua conoscenza soprattutto tra le generazioni più giovani. \nVuoi sapere qualcos'altro della mia città? "],
    r'((.*)[Cc]apitale(.*)([Rr]avenna|citt[aà]|[Ii]mpero)(.*)\??|(.*)([Rr]avenna|citt[aà]|[Ii]mpero)(.*)[Cc]apitale(.*)\??|(.*)stori(.*)[Rr]avenna(.*\??))':["La città di Ravenna è stata eletta per ben tre volte capitale: dell’Impero Romano d’Occidente prima (402-476 d.C), da Teodorico re dei Goti poi (493 – 553 d.C.) e in ultimo dell’impero di Bisanzio in Europa (=Esarcato Bizantino) (584-751), fino alla conquista longobarda della città nel 751 d.C. \nPosso esserti utile in qualche altro modo?"],


    # Regole che sono estremamente generiche
    r'(.*)(((raggiun|arriv)(.*)(città|[rR]avenna))|((città|[rR]avenna)(.*)(raggiun|arriv)))(.*)\??':["Una rete di efficienti collegamenti autostradali, ferroviari e aeroportuali permettono di raggiungere Ravenna con facilità, e da qui collegarsi a tutto il territorio circostante. \nPuoi studiare la scelta che più si addice alle tue esigenze di viaggio a questo link \n https://www.turismo.ra.it/come-arrivare/#:~:text=stradali%20e%20autostradali.-,Da%20Nord,A22%20(Autostrada%20del%20Brennero). "],
    r'((.*)([Cc]osa|[Pp]erch[éèe])(.*)(fare|vedere|visitare)(.*)(cit[aà]|[Rr]avenna)(.*)\??|(.*)tour(.*)(citt[aà]|[Rr]avenna)(.*)\??)':["Otto monumenti UNESCO testimoniano la grandezza e l’importanza della città durante il tempo: Il Mausoleo di Galla Placidia, il Battistero Neoniano (o degli Ortodossi), il Battistero degli Ariani, la Basilica di Sant’Apollinare nuovo, la Cappella Arcivescovile o di Sant’Andrea, il Mausoleo di Teodorico, San Vitale e Sant’Apollinare in Classe. \nImperdibile è inoltre la Domus dei Tappeti di Pietra, uno dei più importanti siti archeologici italiani scoperti negli ultimi decenni, costituita da 14 ambienti pavimentati con mosaici policromi e marmi appartenenti ad un edificio privato bizantino del V-VI secolo. \nNon si può poi passare da Ravenna senza visitare la tomba di Dante e il percorso a lui dedicato. \nPoco fuori Ravenna, infine, si trova Classe, antica sede della flotta imperiale romana, nella quale si possono osservare le antiche rovine dell’insediamento e del porto della città."],
    r'(([Cc]ome|[iI]n che modo)(.*)(visit|eslpor|gir|muov|spost)(.*)(citt[aà]|[Rr]avenna)(.*)\??|([Cc]ome|[iI]n che modo)(.*)(citt[aà]|[Rr]avenna)(.*)(visit|eslpor|gir|muov|spost)(.*)\??|(.*)mezz(.*)(visit|eslpor|gir|muov|spost)(.*)\??)':["Se si vuole girare il centro storico sicuramente muoversi a piedi è la scelta migliore! \nLa città dispone comunque di un sistema funzionante e ben servito di mezzi pubblici, tra cui autobus, biciclette e monopattini elettrici."],
    r'(([Pp]erch[èeé]|[Cc]ome|[Pp]er cosa)(.*)(citt[aà]|[Rr]avenna)(.*)(famosa|nota|conosciuta|ricordata|peculiare)(.*)\??|([Pp]erch[èeé]|[Cc]ome|[Pp]er cosa)(.*)(famosa|nota|conosciuta|ricordata|peculiare)(.*)(citt[aà]|[Rr]avenna)(.*)\??|([Vv]orrei|[Mm]i piacerebbe) (vedere|visitare|andare a) [Rr]avenna\??|[cC]ome andare a [Rr]avenna\??)':["La città di Ravenna è conosciuta in tutto il mondo per la sua storia e i preziosissimi mosaici contenuti nei monumenti presenti in città. Otto monumenti protetti dall’UNESCO testimoniano infatti la sua grandezza e importanza durante il tempo. \nLa città è inoltre famosa per aver accolto il sommo poeta Dante Alighieri. Proprio qui l’autore ha concluso il capolavoro della Divina commedia e ha trovato la morte nel 1321. \nAncora oggi le sue spoglie sono custodite gelosamente nel centro storico della città. \nVuoi sapere qualcos'altro della mia città?"],
    r'([Dd]ov\'[éeè]|[Dd]ove [eéè]|[Dd]ove si trova|[Dd]ove sta) [Rr]avenna\??':["Ravenna è una delle nove province dell'Emilia-Romagna. \nE' la città più grande e storicamente più importante della Romagna; il suo territorio comunale è il secondo in Italia per superficie (Superato solo da quello di Roma) e comporende 9 lidi della riviera romagnola."],
    r'(.*)(meteo|[Cc]he tempo|clima|[Cc]om\'è il tempo)(.*)\??':["A Ravenna c'è sempre il sole! \nSto scherzando ovviamente, purtroppo non sono in grado di conoscere il meteo in tempo reale.", "Aspetta che apro la finestra e controllo... \n... \n... \n... \nNebbia!"],
    r'[Qq]ual(.*)(periodo|momento|stagione)(.*)\??':["Non saprei, ogni stagione sa offrire un lato diverso della città. La mia stagione preferita è la primavera :)"],
    r'[Cc]ome(.*)(chiam|nom)(.*)(persone|gente)(.*)([Rr]avenn)(.*)\??':["Gli abitanti di Ravenna sono i e le Ravennati!"],

    # BONUUUUUUS
    r'(.*)(capelletti|cappelletti)(.*)\??':["I cappelletti sono un formato di pasta all'uovo ripiena tradizionale della cucina romagnola. Si ottengono tagliando la sfoglia di pasta in quadrati, al centro dei quali viene posto il ripieno di formaggio. La pasta viene quindi piegata in due a triangolo, unendo poi, sovrapponendole, due estremità. Vengono serviti tradizionalmente in brodo di carne o al ragù.\nATTENZIONE a non chiedere a Ravenna i tortellini, rischiate una padella in testa! I tortellini sono infatti i cugini emiliani dei cappelletti e sono molto meno buoni (piccolo dissing)."],

    # Interazioni
    r'^([Ss][ìi]|[cC]erto|[Vv]olentieri|[mM]i piacerebbe|[Mm]i farebbe piacere)$':["Splendido! Chiedimi pure tutto quello che vuoi","Sono qui a tua disposizione, chiedi pure!", "Ottimo! sono qui per questo. Cosa ti interessa conoscere?"],
    r'^([oO]k|[Vv]a bene)$':["Splendido! Chiedimi pure tutto quello che vuoi."],
    r'^([Nn]o|[Bb]asta|è sufficiente|[sS]ono (a posto|apposto) cos[ìi]|[Nn]o (grazie|(.*)è sufficiente|(.*)basta)|[sS]ono (a posto|apposto))$':["Va bene, spero di essere stata utile, se vuoi chiudere la conversazione digita 'Chiudi'", "Ottimo, è stato un piacere parlare con te. Se vuoi chiudere la conversazione digita 'Chiudi'", "Se vuoi chiudere la conversazione digita 'Chiudi'"],
    r'^([Gg]razie(.*))':["Prego! è sempre un piacere aiutare. C'è altro che posso fare per te?"]
}